/**
 * GDAX Product Order API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gdax.service.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ProductBookResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-11T10:49:09.161-05:00")
public class ProductBookResponse   {
  @SerializedName("sequence")
  private String sequence = null;

  @SerializedName("bids")
  private List<List<String>> bids = new ArrayList<List<String>>();

  @SerializedName("asks")
  private List<List<String>> asks = new ArrayList<List<String>>();

  public ProductBookResponse sequence(String sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Get sequence
   * @return sequence
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSequence() {
    return sequence;
  }

  public void setSequence(String sequence) {
    this.sequence = sequence;
  }

  public ProductBookResponse bids(List<List<String>> bids) {
    this.bids = bids;
    return this;
  }

  public ProductBookResponse addBidsItem(List<String> bidsItem) {
    this.bids.add(bidsItem);
    return this;
  }

   /**
   * Get bids
   * @return bids
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<List<String>> getBids() {
    return bids;
  }

  public void setBids(List<List<String>> bids) {
    this.bids = bids;
  }

  public ProductBookResponse asks(List<List<String>> asks) {
    this.asks = asks;
    return this;
  }

  public ProductBookResponse addAsksItem(List<String> asksItem) {
    this.asks.add(asksItem);
    return this;
  }

   /**
   * Get asks
   * @return asks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<List<String>> getAsks() {
    return asks;
  }

  public void setAsks(List<List<String>> asks) {
    this.asks = asks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductBookResponse productBookResponse = (ProductBookResponse) o;
    return Objects.equals(this.sequence, productBookResponse.sequence) &&
        Objects.equals(this.bids, productBookResponse.bids) &&
        Objects.equals(this.asks, productBookResponse.asks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequence, bids, asks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductBookResponse {\n");
    
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    bids: ").append(toIndentedString(bids)).append("\n");
    sb.append("    asks: ").append(toIndentedString(asks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

