/**
 * GDAX Product Order API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gdax.service.client.api;

import com.gdax.service.ApiException;
import com.gdax.service.client.model.ProductBookResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    
    /**
     * Book fors selected product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsProductIdBookGetTest() throws ApiException {
        String productId = null;
        String level = null;
        // ProductBookResponse response = api.productsProductIdBookGet(productId, level);

        // TODO: test validations
    }
    
}
