/**
 * Quote Service API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.dmytrobr.quoteservice.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * QuoteResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-10T14:58:44.750-05:00")
public class QuoteResponse   {
  @SerializedName("price")
  private String price = null;

  @SerializedName("total")
  private String total = null;

  @SerializedName("currency")
  private String currency = null;

  public QuoteResponse price(String price) {
    this.price = price;
    return this;
  }

   /**
   * The per-unit cost of the base currency
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "The per-unit cost of the base currency")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public QuoteResponse total(String total) {
    this.total = total;
    return this;
  }

   /**
   * Total quantity of quote currency
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "Total quantity of quote currency")
  public String getTotal() {
    return total;
  }

  public void setTotal(String total) {
    this.total = total;
  }

  public QuoteResponse currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * The quote currency
   * @return currency
  **/
  @ApiModelProperty(example = "null", value = "The quote currency")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteResponse quoteResponse = (QuoteResponse) o;
    return Objects.equals(this.price, quoteResponse.price) &&
        Objects.equals(this.total, quoteResponse.total) &&
        Objects.equals(this.currency, quoteResponse.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, total, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteResponse {\n");
    
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

