swagger: '2.0'
info:
  title: GDAX Product Order API
  version: "1.0.0"
# the domain of the service
host: api.gdax.com
# array of all schemes that your API supports
schemes:
  - https

produces:
  - application/json
paths:
  '/products/{productId}/book':
    get:
      operationId: getProductOrderBook
      summary: Book fors selected product
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          type: string
          required: true
        - name: level
          in: query
          type: string
      responses:
        200:
          description: Producs bids
          schema:
            $ref: '#/definitions/ProductBookResponse'


definitions:
  ProductBookResponse:
    type: object
    properties:
      sequence:
        type: string
      bids:
        type: array
        items:
          type: array
          items:
            type: string
      asks:
        type: array
        items:
          type: array
          items:
            type: string
  Bid:
    type: object
    properties:
      price:
        type: number
        format: double
      size:
        type: number
        format: double
      num-orders:
        type: integer
        format: int32

          
